export const FETCHING_NEWS = 'FETCHING_NEWS';
export const FETCHING_NEWS_SUCCESS = 'FETCHING_NEWS_SUCCESS';
export const FETCHING_NEWS_FAILURE = 'FETCHING_NEWS_FAILURE';
export const FETCHING_NEW_NEWS_SUCCESS = 'FETCHING_NEW_NEWS_SUCCESS';
export const FETCHING_NEW_NEWS = 'FETCHING_NEW_NEWS';

export const FETCHING_COMMENTS = 'FETCHING_COMMENTS';
export const FETCHING_COMMENTS_FAILURE = 'FETCHING_COMMENTS_FAILURE';
export const FETCHING_COMMENTS_SUCCESS = 'FETCHING_COMMENTS_SUCCESS';

export const FETCHING_SEARCH = 'FETCHING_SEARCH';
export const FETCHING_SEARCH_SUCCESS = 'FETCHING_SEARCH_SUCCESS';
export const FETCHING_SEARCH_FAILURE = 'FETCHING_SEARCH_FAILURE';
export const FETCHING_MORE_SEARCH__SUCCESS = 'FETCHING_MORE_SEARCH__SUCCESS';
export const FETCHING_MORE_SEARCH = 'FETCHING_MORE_SEARCH';

export const SAVED_LIST_FETCH = 'SAVED_LIST_FETCH';
export const SAVED_LIST_ADD = 'SAVED_LIST_ADD';
export const SAVED_LIST_REMOVE = 'SAVED_LIST_REMOVE';
