export const FETCHING_NEWS = 'FETCHING_NEWS';
export const FETCHING_NEWS_SUCCESS = 'FETCHING_NEWS_SUCCESS';
export const FETCHING_NEWS_FAILURE = 'FETCHING_NEWS_FAILURE';
export const FETCHING_NEW_NEWS_SUCCESS = 'FETCHING_NEW_NEWS_SUCCESS';
export const FETCHING_NEW_NEWS = 'FETCHING_NEW_NEWS';

export const FETCHING_COMMENTS = 'FETCHING_COMMENTS';
export const FETCHING_COMMENTS_FAILURE = 'FETCHING_COMMENTS_FAILURE';
export const FETCHING_COMMENTS_SUCCESS = 'FETCHING_COMMENTS_SUCCESS';
